version: '3'
services:
  postgis:
    image: postgis/postgis
    container_name: my-postgis-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgis_data:/var/lib/postgresql/data
    networks:
      - postgis_network

networks:
  postgis_network: